services:
  rss-fetcher:
    build: .
    volumes:
      - ./config/feeds.yaml:/app/config/feeds.yaml
      - ./config/webhooks.yaml:/app/config/webhooks.yaml
    depends_on:
      - valkey
    restart: always

  valkey:
    image: valkey/valkey:9.0.1-alpine3.23
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data

volumes:
  valkey-data:
